observations: # for now "observations" must be on top level, will be removed
  multiple: # automatically pad the datasets with the min and max dates, will be renamed to "zip"
    - dataset: observations-od-ai-0001-2017-2022-meteosat-8-iodc-seviri-v1
      frequency: 6h             # this may become optional
      window: (-6, 0)           # this may become optional
      rename_prefix: "seviri"   # this may become optional
      is_observations: true     # will desappear
    - dataset: observations-ea-ofb-0001-2004-2023-combined-metar-v1
      frequency: 6h             # this may become optional
      window: (-6, 0)           # this may become optional
      rename_prefix: "land"     # this may become optional
      is_observations: true     # will disappear
    - dataset: observations-ea-ofb-0001-2018-2023-noaa-20-atms-radiances-v1
      frequency: 6h              # this may become optional
      window: (-6, 0)           # this may become optional
      rename_prefix: "noaa_atms" # this may become optional
      is_observations: true      # will desappear
    - dataset: aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6
      start: 2004-11-09 00:00:00
      end: 2023-12-31 00:00:00
